# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31fbd0e1273a560e9a0066ba73d9326d4e489ec99ce1ee63ddee10772d4f4755ec5772bb0c76eba46d2e7ceb7509b8dc8fdc6b78b8befed0ac9938d201a943c7

test:
  secret_key_base: 9458c6545963300bad72a8441e3eb7cfb2c86bbe3ee6f30044919f9749ba38f72cbc9f039d0f7556611307f28696a30f99ec47837e594ab072f3668762ad3d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
